version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/project/static
      - ./media/:/project/media

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: deploy_db_name
      MYSQL_USER: deploy_db_user
      MYSQL_PASSWORD: Myw8VVn8oOPzldO2dis6pyrAb

#  redis:
#    image: redis:3.0.6
#    restart: "on-failure"
#    container_name: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redisdb:/var/lib/redis
