version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: deploy_db_name
      MYSQL_USER: deploy_db_user
      MYSQL_PASSWORD: Myw8VVn8oOPzldO2dis6pyrAb

#  redis:
#    image: redis:3.0.6
#    restart: "on-failure"
#    container_name: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redisdb:/var/lib/redis
