version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    links:
     - db
#  redis:
#    image: redis:3.0.6
#    restart: "on-failure"
#    container_name: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./redisdb:/var/lib/redis
